export type Language = "vi" | "en";
export type ViewMode = "week" | "month" | "semester" | "year";
export type CourseKind = "course" | "research" | "practice" | "thesis" | "elective";
export type Assessment = "credit" | "exam" | "exam-coursework" | "credit-coursework" | "graded-credit" | "coursework" | "none" | "defense";

export type LocalizedText = {
  vi: string;
  en: string;
};

export type Course = {
  id: string;
  semester: 1 | 2 | 3 | 4;
  ru: string;
  title: LocalizedText;
  credits: number;
  hours: number;
  contactHours: number;
  assessment: Assessment;
  kind: CourseKind;
  officialNote?: LocalizedText;
  analysis: LocalizedText;
  prepare: LocalizedText;
  outcome: LocalizedText;
};

export const semesterMeta = {
  1: { weeks: 17, credits: 30, weeklyLoad: 51.4, weeklyContact: 18, coursework: 3, exams: 4 },
  2: { weeks: 17, credits: 30, weeklyLoad: 48.6, weeklyContact: 17, coursework: 1, exams: 4 },
  3: { weeks: 17, credits: 30, weeklyLoad: 51.4, weeklyContact: 17, coursework: 2, exams: 3 },
  4: { weeks: 11, credits: 30, weeklyLoad: 54, weeklyContact: 10, coursework: 1, exams: 3 },
} as const;

export const courses: readonly Course[] = [
  {
    id: "foreign-1",
    semester: 1,
    ru: "Иностранный язык",
    title: { vi: "Ngoại ngữ", en: "Foreign Language" },
    credits: 2,
    hours: 72,
    contactHours: 34,
    assessment: "credit",
    kind: "course",
    officialNote: { vi: "Môn Ngoại ngữ tiếp tục thêm 2 tín chỉ ở học kỳ 2.", en: "The Foreign Language course continues for another 2 credits in semester 2." },
    analysis: { vi: "Rèn ngoại ngữ học thuật và giao tiếp phục vụ học tập sau đại học.", en: "Builds academic and study-oriented foreign-language communication." },
    prepare: { vi: "Ôn từ vựng học thuật, nghe hiểu bài giảng và kỹ năng đọc tài liệu.", en: "Review academic vocabulary, lecture listening and technical reading." },
    outcome: { vi: "Đọc, trao đổi và trình bày nội dung học thuật tự tin hơn.", en: "Read, discuss and present academic material more confidently." },
  },
  {
    id: "methodology",
    semester: 1,
    ru: "Методология научного познания",
    title: { vi: "Phương pháp luận nghiên cứu khoa học", en: "Methodology of Scientific Knowledge" },
    credits: 2,
    hours: 72,
    contactHours: 34,
    assessment: "credit",
    kind: "course",
    analysis: { vi: "Học cách đặt vấn đề, hình thành giả thuyết, chọn phương pháp và lập luận khoa học.", en: "Covers research questions, hypotheses, methods and scientific argumentation." },
    prepare: { vi: "Làm quen cấu trúc bài báo, trích dẫn và cách đọc tài liệu nghiên cứu.", en: "Become familiar with papers, citations and research reading." },
    outcome: { vi: "Biết thiết kế và trình bày một nghiên cứu có cấu trúc.", en: "Can structure and communicate a research study." },
  },
  {
    id: "analytical-models",
    semester: 1,
    ru: "Аналитические модели автоматизированных систем обработки информации и управления",
    title: { vi: "Mô hình giải tích của hệ thống tự động xử lý thông tin và điều khiển", en: "Analytical Models of Automated Information Processing and Control Systems" },
    credits: 4,
    hours: 144,
    contactHours: 34,
    assessment: "credit-coursework",
    kind: "course",
    analysis: { vi: "Mô hình hóa hệ thống, mô tả quan hệ đầu vào–đầu ra và phân tích hành vi hệ thống.", en: "Models systems, input–output relationships and system behavior." },
    prepare: { vi: "Ôn toán kỹ thuật, đại số tuyến tính, hệ thống điều khiển và mô hình trạng thái.", en: "Review engineering mathematics, linear algebra, control systems and state-space models." },
    outcome: { vi: "Có thể xây dựng và phân tích mô hình toán cho hệ thống tự động.", en: "Can formulate and analyze mathematical models of automated systems." },
  },
  {
    id: "multivariate",
    semester: 1,
    ru: "Многомерный анализ данных в системах искусственного интеллекта",
    title: { vi: "Phân tích dữ liệu đa chiều trong hệ thống AI", en: "Multivariate Data Analysis in AI Systems" },
    credits: 5,
    hours: 180,
    contactHours: 51,
    assessment: "exam-coursework",
    kind: "course",
    analysis: { vi: "Làm việc với dữ liệu nhiều đặc trưng: tương quan, không gian nhiều chiều, giảm chiều và phân tích mẫu.", en: "Works with high-dimensional data, correlation, dimensionality reduction and pattern analysis." },
    prepare: { vi: "Ưu tiên đại số tuyến tính, xác suất thống kê, Python, NumPy và Pandas.", en: "Prioritize linear algebra, probability/statistics, Python, NumPy and Pandas." },
    outcome: { vi: "Có thể chuẩn bị và phân tích dữ liệu nhiều chiều cho các bài toán AI.", en: "Can prepare and analyze multivariate data for AI problems." },
  },
  {
    id: "oop",
    semester: 1,
    ru: "Объектно-ориентированное проектирование автоматизированных систем обработки информации и управления",
    title: { vi: "Thiết kế hướng đối tượng hệ thống tự động xử lý thông tin và điều khiển", en: "Object-Oriented Design of Automated Information Processing and Control Systems" },
    credits: 6,
    hours: 216,
    contactHours: 51,
    assessment: "exam-coursework",
    kind: "course",
    analysis: { vi: "Thiết kế phần mềm theo class/object, abstraction, interface, UML và kiến trúc hệ thống.", en: "Software design with classes/objects, abstraction, interfaces, UML and system architecture." },
    prepare: { vi: "Cần học chắc lập trình cơ bản, OOP, Git và tư duy thiết kế module.", en: "Build solid programming basics, OOP, Git and modular design skills." },
    outcome: { vi: "Thiết kế được cấu trúc phần mềm lớn hơn thay vì chỉ viết đoạn code rời.", en: "Can design larger software structures rather than isolated code snippets." },
  },
  {
    id: "db-optimization",
    semester: 1,
    ru: "Оптимизация баз данных систем машинного обучения",
    title: { vi: "Tối ưu cơ sở dữ liệu cho hệ thống Machine Learning", en: "Database Optimization for Machine-Learning Systems" },
    credits: 4,
    hours: 144,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Nối kiến thức database với nhu cầu lưu, truy vấn và cung cấp dữ liệu cho pipeline ML.", en: "Connects database design and query performance with machine-learning data pipelines." },
    prepare: { vi: "Học SQL, bảng/khóa, JOIN, index, normalization, transaction và query plan.", en: "Learn SQL, keys, JOINs, indexes, normalization, transactions and query plans." },
    outcome: { vi: "Biết tổ chức và tối ưu dữ liệu phục vụ huấn luyện, phân tích và suy luận.", en: "Can organize and optimize data for training, analytics and inference." },
  },
  {
    id: "software-1",
    semester: 1,
    ru: "Технологии разработки программного обеспечения — часть 1",
    title: { vi: "Công nghệ phát triển phần mềm — phần 1", en: "Software Development Technologies — Part 1" },
    credits: 4,
    hours: 144,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    officialNote: { vi: "Môn có tổng 6 tín chỉ; 2 tín chỉ còn lại nằm ở học kỳ 2 dưới dạng coursework.", en: "The full course is 6 credits; the remaining 2 credits are in semester 2 as coursework." },
    analysis: { vi: "Quy trình phát triển phần mềm: yêu cầu, thiết kế, code, kiểm thử, version control và tổ chức dự án.", en: "Software lifecycle: requirements, design, coding, testing, version control and project organization." },
    prepare: { vi: "Git/GitHub, cấu trúc dự án, testing cơ bản và một ngôn ngữ lập trình chính.", en: "Git/GitHub, project structure, basic testing and one primary programming language." },
    outcome: { vi: "Có thể tham gia một quy trình phát triển phần mềm có tổ chức.", en: "Can work within a structured software-development workflow." },
  },
  {
    id: "nir-1",
    semester: 1,
    ru: "Научно-исследовательская работа (НИР)",
    title: { vi: "Nghiên cứu khoa học (NIR)", en: "Research Work (NIR)" },
    credits: 3,
    hours: 108,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "research",
    analysis: { vi: "Bắt đầu tích lũy hướng nghiên cứu ngay từ học kỳ đầu, không chờ đến năm cuối.", en: "Starts the research track in the first semester rather than waiting until the final year." },
    prepare: { vi: "Tập đọc paper, ghi chú nguồn, đặt câu hỏi nghiên cứu và lưu nhật ký thực nghiệm.", en: "Practice reading papers, recording sources, framing questions and keeping experiment notes." },
    outcome: { vi: "Hình thành nền tảng đề tài và thói quen nghiên cứu liên tục.", en: "Builds the foundation for a thesis topic and continuous research habits." },
  },

  {
    id: "foreign-2",
    semester: 2,
    ru: "Иностранный язык",
    title: { vi: "Ngoại ngữ", en: "Foreign Language" },
    credits: 2,
    hours: 72,
    contactHours: 34,
    assessment: "credit",
    kind: "course",
    analysis: { vi: "Tiếp tục ngoại ngữ học thuật, tập trung sử dụng trong môi trường học và nghiên cứu.", en: "Continues academic language for study and research contexts." },
    prepare: { vi: "Duy trì nghe, đọc và trình bày nội dung chuyên ngành.", en: "Keep practicing technical listening, reading and presentation." },
    outcome: { vi: "Sử dụng ngoại ngữ ổn định hơn trong học thuật.", en: "Uses the foreign language more consistently in academic work." },
  },
  {
    id: "entrepreneurship",
    semester: 2,
    ru: "Основы предпринимательства",
    title: { vi: "Cơ sở khởi nghiệp", en: "Fundamentals of Entrepreneurship" },
    credits: 2,
    hours: 72,
    contactHours: 34,
    assessment: "credit",
    kind: "course",
    analysis: { vi: "Kiến thức nền về mô hình kinh doanh, sản phẩm và thương mại hóa ý tưởng.", en: "Introduces business models, products and commercialization of ideas." },
    prepare: { vi: "Không cần kỹ thuật sâu; nên hiểu sản phẩm và người dùng.", en: "No deep technical prerequisite; basic product and user thinking helps." },
    outcome: { vi: "Biết nhìn một ý tưởng kỹ thuật dưới góc độ sản phẩm và thị trường.", en: "Can view a technical idea through product and market lenses." },
  },
  {
    id: "ml",
    semester: 2,
    ru: "Методы машинного обучения в автоматизированных системах обработки информации и управления",
    title: { vi: "Phương pháp Machine Learning trong hệ thống tự động", en: "Machine-Learning Methods in Automated Information Processing and Control Systems" },
    credits: 3,
    hours: 108,
    contactHours: 68,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Học các mô hình ML nền tảng và cách tích hợp chúng vào hệ thống tự động.", en: "Covers core ML models and their use inside automated systems." },
    prepare: { vi: "Python, NumPy/Pandas, xác suất thống kê, đại số tuyến tính và đánh giá mô hình.", en: "Python, NumPy/Pandas, probability/statistics, linear algebra and model evaluation." },
    outcome: { vi: "Có thể xây dựng pipeline ML cơ bản từ dữ liệu đến đánh giá.", en: "Can build a basic ML pipeline from data to evaluation." },
  },
  {
    id: "reliability",
    semester: 2,
    ru: "Модели надёжности АСОИУ",
    title: { vi: "Mô hình độ tin cậy của ASOIU", en: "Reliability Models of AIPCS" },
    credits: 3,
    hours: 108,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Phân tích xác suất hỏng, độ sẵn sàng và cấu trúc độ tin cậy của hệ thống.", en: "Analyzes failure probability, availability and system reliability structures." },
    prepare: { vi: "Ôn xác suất, thống kê và mô hình hệ thống nối tiếp/song song.", en: "Review probability, statistics and series/parallel system models." },
    outcome: { vi: "Đánh giá được mức tin cậy và rủi ro vận hành của hệ thống.", en: "Can evaluate system reliability and operational risk." },
  },
  {
    id: "postrelational",
    semester: 2,
    ru: "Постреляционные базы данных",
    title: { vi: "Cơ sở dữ liệu hậu quan hệ", en: "Post-Relational Databases" },
    credits: 4,
    hours: 144,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Mở rộng khỏi mô hình quan hệ truyền thống sang các mô hình dữ liệu hiện đại.", en: "Extends beyond traditional relational databases into modern data models." },
    prepare: { vi: "Phải chắc SQL và database quan hệ trước; sau đó mới học NoSQL/graph/document.", en: "First master SQL and relational databases, then move to NoSQL/graph/document models." },
    outcome: { vi: "Biết chọn mô hình dữ liệu phù hợp cho từng bài toán.", en: "Can choose a suitable data model for different workloads." },
  },
  {
    id: "neural",
    semester: 2,
    ru: "Разработка нейросетевых систем",
    title: { vi: "Phát triển hệ thống mạng nơ-ron", en: "Development of Neural-Network Systems" },
    credits: 4,
    hours: 144,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Từ mạng nơ-ron cơ bản đến huấn luyện, loss, gradient và xây dựng hệ thống neural.", en: "From basic neural networks to training, loss functions, gradients and neural-system development." },
    prepare: { vi: "ML cơ bản, Python, đại số tuyến tính và đạo hàm/gradient.", en: "Basic ML, Python, linear algebra and derivatives/gradients." },
    outcome: { vi: "Có thể thiết kế và huấn luyện mô hình neural ở mức nền tảng.", en: "Can design and train foundational neural models." },
  },
  {
    id: "software-2",
    semester: 2,
    ru: "Технологии разработки программного обеспечения — часть 2",
    title: { vi: "Công nghệ phát triển phần mềm — phần 2", en: "Software Development Technologies — Part 2" },
    credits: 2,
    hours: 72,
    contactHours: 0,
    assessment: "coursework",
    kind: "course",
    analysis: { vi: "Phần coursework của môn phát triển phần mềm, tập trung sản phẩm và tài liệu hóa.", en: "Coursework continuation focused on delivering and documenting a software product." },
    prepare: { vi: "Hoàn thiện kỹ năng Git, testing, kiến trúc và viết tài liệu kỹ thuật.", en: "Strengthen Git, testing, architecture and technical documentation." },
    outcome: { vi: "Hoàn thành một sản phẩm/coursework có cấu trúc.", en: "Completes a structured software coursework deliverable." },
  },
  {
    id: "project-practice",
    semester: 2,
    ru: "Проектно-технологическая практика",
    title: { vi: "Thực tập dự án – công nghệ", en: "Project and Technology Practice" },
    credits: 2,
    hours: 72,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "practice",
    analysis: { vi: "Chuyển kiến thức lý thuyết thành nhiệm vụ dự án có sản phẩm đầu ra.", en: "Applies theory to project tasks with concrete deliverables." },
    prepare: { vi: "Quản lý task, Git, báo cáo tiến độ và làm việc theo milestone.", en: "Task management, Git, progress reporting and milestone-based work." },
    outcome: { vi: "Biết tổ chức và bàn giao công việc dự án kỹ thuật.", en: "Can organize and deliver technical project work." },
  },
  {
    id: "operations-practice",
    semester: 2,
    ru: "Эксплуатационная практика",
    title: { vi: "Thực tập vận hành hệ thống", en: "Operational Practice" },
    credits: 3,
    hours: 108,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "practice",
    analysis: { vi: "Tập trung triển khai, vận hành, giám sát và xử lý tình huống hệ thống.", en: "Focuses on deployment, operation, monitoring and real-system handling." },
    prepare: { vi: "Linux cơ bản, log, cấu hình và tư duy xử lý sự cố.", en: "Basic Linux, logs, configuration and troubleshooting mindset." },
    outcome: { vi: "Có khả năng vận hành và kiểm tra hệ thống thực tế tốt hơn.", en: "Improves practical system-operation and verification skills." },
  },
  {
    id: "pedagogy-1",
    semester: 2,
    ru: "Педагогическая практика — часть 1",
    title: { vi: "Thực tập sư phạm — phần 1", en: "Pedagogical Practice — Part 1" },
    credits: 1,
    hours: 36,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "practice",
    analysis: { vi: "Rèn cách giải thích, trình bày và tổ chức nội dung chuyên môn.", en: "Builds skills in explaining, presenting and structuring technical content." },
    prepare: { vi: "Luyện trình bày ngắn, slide và cách giải thích khái niệm.", en: "Practice short presentations, slides and concept explanations." },
    outcome: { vi: "Trình bày kiến thức có cấu trúc và dễ hiểu hơn.", en: "Communicates knowledge in a clearer, more structured way." },
  },
  {
    id: "nir-2",
    semester: 2,
    ru: "Научно-исследовательская работа (НИР)",
    title: { vi: "Nghiên cứu khoa học (NIR)", en: "Research Work (NIR)" },
    credits: 4,
    hours: 144,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "research",
    analysis: { vi: "Tăng khối lượng nghiên cứu và kết nối dần với hướng luận văn.", en: "Expands research workload and progressively connects it to the thesis direction." },
    prepare: { vi: "Duy trì kho tài liệu, code thí nghiệm và tiêu chí đánh giá.", en: "Maintain a literature base, experiment code and evaluation criteria." },
    outcome: { vi: "Có kết quả nghiên cứu trung gian có thể tái sử dụng cho luận văn.", en: "Produces intermediate research results reusable in the thesis." },
  },

  {
    id: "time-series",
    semester: 3,
    ru: "Анализ временных рядов",
    title: { vi: "Phân tích chuỗi thời gian", en: "Time-Series Analysis" },
    credits: 4,
    hours: 144,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Phân tích dữ liệu theo thời gian: xu hướng, mùa vụ, dự báo và phát hiện bất thường.", en: "Analyzes temporal data: trends, seasonality, forecasting and anomaly detection." },
    prepare: { vi: "Xác suất thống kê, Python và tư duy tín hiệu/chuỗi thời gian.", en: "Probability/statistics, Python and signal/time-series thinking." },
    outcome: { vi: "Có thể xây dựng quy trình phân tích và dự báo dữ liệu thời gian.", en: "Can build analysis and forecasting workflows for temporal data." },
  },
  {
    id: "business-ai",
    semester: 3,
    ru: "Искусственный интеллект в задачах бизнес-аналитики",
    title: { vi: "AI trong bài toán Business Analytics", en: "Artificial Intelligence for Business Analytics" },
    credits: 4,
    hours: 144,
    contactHours: 51,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Dùng AI và dữ liệu để hỗ trợ phân tích, dự báo và quyết định kinh doanh.", en: "Uses AI and data for business analysis, forecasting and decision support." },
    prepare: { vi: "ML cơ bản, xử lý dữ liệu và khả năng diễn giải kết quả.", en: "Basic ML, data processing and result interpretation." },
    outcome: { vi: "Biết biến dữ liệu thành insight và hỗ trợ quyết định.", en: "Can turn data into insights and decision support." },
  },
  {
    id: "is-management",
    semester: 3,
    ru: "Управление проектированием информационных систем",
    title: { vi: "Quản lý thiết kế hệ thống thông tin", en: "Management of Information-System Design" },
    credits: 3,
    hours: 108,
    contactHours: 51,
    assessment: "credit",
    kind: "course",
    analysis: { vi: "Quản lý yêu cầu, thiết kế, tiến độ và chất lượng khi xây dựng hệ thống thông tin.", en: "Manages requirements, design, schedule and quality in information-system projects." },
    prepare: { vi: "Software engineering, kiến trúc hệ thống và quản lý task.", en: "Software engineering, system architecture and task management." },
    outcome: { vi: "Có thể lập kế hoạch và kiểm soát một dự án hệ thống thông tin.", en: "Can plan and control an information-system project." },
  },
  {
    id: "nir-data",
    semester: 3,
    ru: "НИР по обработке и анализу данных",
    title: { vi: "Nghiên cứu về xử lý và phân tích dữ liệu", en: "Research in Data Processing and Analysis" },
    credits: 2,
    hours: 72,
    contactHours: 0,
    assessment: "coursework",
    kind: "research",
    analysis: { vi: "Môn nghiên cứu chuyên biệt về xử lý dữ liệu, có coursework riêng.", en: "A focused research course on data processing and analysis with coursework." },
    prepare: { vi: "Python, thống kê, xử lý dữ liệu và phương pháp nghiên cứu.", en: "Python, statistics, data processing and research methodology." },
    outcome: { vi: "Tạo được một nghiên cứu nhỏ có dữ liệu, phương pháp và kết quả rõ ràng.", en: "Produces a small study with clear data, method and results." },
  },
  {
    id: "ergonomics",
    semester: 3,
    ru: "Эргономический анализ систем обработки и отображения информации",
    title: { vi: "Phân tích công thái học hệ thống xử lý và hiển thị thông tin", en: "Ergonomic Analysis of Information Processing and Display Systems" },
    credits: 6,
    hours: 216,
    contactHours: 68,
    assessment: "exam-coursework",
    kind: "course",
    analysis: { vi: "Phân tích cách con người tương tác với hệ thống, giao diện và hiển thị thông tin.", en: "Studies human interaction with systems, interfaces and information displays." },
    prepare: { vi: "HMI/UI, hệ thống thông tin và tư duy human factors.", en: "HMI/UI, information systems and human-factors thinking." },
    outcome: { vi: "Biết đánh giá giao diện/hệ thống theo hiệu quả sử dụng và tải nhận thức.", en: "Can evaluate interfaces and systems for usability and cognitive load." },
  },
  {
    id: "elective-1",
    semester: 3,
    ru: "Дисциплина по выбору №1",
    title: { vi: "Môn tự chọn số 1: Bảo vệ/An toàn thông tin", en: "Elective 1: Information Protection / Security" },
    credits: 3,
    hours: 108,
    contactHours: 68,
    assessment: "credit",
    kind: "elective",
    officialNote: {
      vi: "Kế hoạch đưa ra hai lựa chọn: «Защита информации…» hoặc «Информационная безопасность…».",
      en: "The plan lists two alternatives: “Information Protection…” or “Information Security…”.",
    },
    analysis: { vi: "Bổ sung góc nhìn bảo mật cho hệ thống tự động xử lý thông tin và điều khiển.", en: "Adds a security perspective to automated information-processing and control systems." },
    prepare: { vi: "Network cơ bản, authentication, authorization, threat model và bảo mật dữ liệu.", en: "Basic networking, authentication, authorization, threat modeling and data security." },
    outcome: { vi: "Nhận diện và giảm rủi ro bảo mật trong hệ thống.", en: "Can identify and reduce security risks in systems." },
  },
  {
    id: "pedagogy-2",
    semester: 3,
    ru: "Педагогическая практика — часть 2",
    title: { vi: "Thực tập sư phạm — phần 2", en: "Pedagogical Practice — Part 2" },
    credits: 1,
    hours: 36,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "practice",
    analysis: { vi: "Tiếp tục thực hành trình bày và hướng dẫn nội dung chuyên môn.", en: "Continues practice in teaching and presenting technical material." },
    prepare: { vi: "Chuẩn bị bài trình bày, ví dụ minh họa và phản hồi người học.", en: "Prepare presentations, examples and learner feedback." },
    outcome: { vi: "Nâng khả năng truyền đạt và hướng dẫn học thuật.", en: "Improves academic communication and instruction." },
  },
  {
    id: "nir-3",
    semester: 3,
    ru: "Научно-исследовательская работа (НИР)",
    title: { vi: "Nghiên cứu khoa học (NIR)", en: "Research Work (NIR)" },
    credits: 7,
    hours: 252,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "research",
    analysis: { vi: "Khối lượng NIR tăng mạnh; đây là giai đoạn nên chốt hướng và kiến trúc luận văn.", en: "Research workload rises sharply; this is the stage to lock in the thesis direction and structure." },
    prepare: { vi: "Đề tài, dataset, baseline, metric và kế hoạch thí nghiệm phải rõ.", en: "Clarify the topic, dataset, baseline, metrics and experiment plan." },
    outcome: { vi: "Có phần lớn bằng chứng/kết quả nền cho luận văn.", en: "Builds a substantial body of evidence and results for the thesis." },
  },

  {
    id: "mivar",
    semester: 4,
    ru: "Миварные технологии логического искусственного интеллекта",
    title: { vi: "Công nghệ Mivar của AI logic", en: "Mivar Technologies of Logical Artificial Intelligence" },
    credits: 4,
    hours: 144,
    contactHours: 33,
    assessment: "exam-coursework",
    kind: "course",
    analysis: { vi: "Hướng AI dựa trên tri thức, luật và suy luận logic; khác với mạng nơ-ron.", en: "A knowledge-, rule- and inference-based AI direction distinct from neural networks." },
    prepare: { vi: "Logic, biểu diễn tri thức, graph và tư duy rule-based.", en: "Logic, knowledge representation, graphs and rule-based reasoning." },
    outcome: { vi: "Hiểu cách xây dựng hệ suy luận logic cho bài toán AI.", en: "Understands how to build logical inference systems for AI tasks." },
  },
  {
    id: "lifecycle",
    semester: 4,
    ru: "Описание процессов жизненного цикла СТС",
    title: { vi: "Mô tả quy trình vòng đời hệ thống kỹ thuật phức tạp", en: "Description of Complex Technical-System Lifecycle Processes" },
    credits: 4,
    hours: 144,
    contactHours: 33,
    assessment: "exam",
    kind: "course",
    analysis: { vi: "Theo dõi hệ thống từ yêu cầu, thiết kế, kiểm thử đến vận hành và bảo trì.", en: "Covers the system lifecycle from requirements and design through testing, operation and maintenance." },
    prepare: { vi: "Systems engineering, software lifecycle và quản lý cấu hình.", en: "Systems engineering, software lifecycle and configuration management." },
    outcome: { vi: "Có thể mô tả và kiểm soát các giai đoạn vòng đời hệ thống.", en: "Can describe and manage stages of a system lifecycle." },
  },
  {
    id: "elective-2",
    semester: 4,
    ru: "Дисциплина по выбору №2",
    title: { vi: "Môn tự chọn số 2: Big Data hoặc Multimedia", en: "Elective 2: Big Data or Multimedia Systems" },
    credits: 3,
    hours: 108,
    contactHours: 44,
    assessment: "exam",
    kind: "elective",
    officialNote: {
      vi: "Chọn «Технологии обработки больших данных» hoặc «Технологии разработки мультимедиа систем».",
      en: "Choose “Big Data Processing Technologies” or “Multimedia Systems Development Technologies”.",
    },
    analysis: { vi: "Cho phép đi sâu theo hướng dữ liệu lớn hoặc phát triển hệ thống multimedia.", en: "Allows specialization toward big-data processing or multimedia-system development." },
    prepare: { vi: "Nếu chọn Big Data: database/distributed data. Nếu chọn Multimedia: software + media processing.", en: "For Big Data: databases/distributed data. For Multimedia: software and media processing." },
    outcome: { vi: "Bổ sung chuyên môn theo hướng gần với đề tài hoặc nghề nghiệp mong muốn.", en: "Adds specialization aligned with the intended thesis or career direction." },
  },
  {
    id: "prediploma",
    semester: 4,
    ru: "Преддипломная практика",
    title: { vi: "Thực tập trước tốt nghiệp", en: "Pre-Diploma Practice" },
    credits: 3,
    hours: 108,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "practice",
    analysis: { vi: "Gom dữ liệu, code, thực nghiệm và tài liệu để chuyển thành luận văn hoàn chỉnh.", en: "Consolidates data, code, experiments and documentation into a complete thesis." },
    prepare: { vi: "Repo code sạch, kết quả tái lập được và cấu trúc luận văn đã ổn định.", en: "Clean code repository, reproducible results and a stable thesis structure." },
    outcome: { vi: "Có bộ tài liệu và kết quả sẵn sàng cho giai đoạn bảo vệ.", en: "Produces a package of results and documentation ready for defense." },
  },
  {
    id: "nir-4",
    semester: 4,
    ru: "Научно-исследовательская работа (НИР)",
    title: { vi: "Nghiên cứu khoa học (NIR)", en: "Research Work (NIR)" },
    credits: 7,
    hours: 252,
    contactHours: 0,
    assessment: "graded-credit",
    kind: "research",
    analysis: { vi: "Hoàn thiện thực nghiệm, đánh giá và kết luận nghiên cứu.", en: "Finalizes experiments, evaluation and research conclusions." },
    prepare: { vi: "Chốt metric, ablation/so sánh, biểu đồ và diễn giải kết quả.", en: "Finalize metrics, comparisons/ablations, figures and result interpretation." },
    outcome: { vi: "Có kết quả nghiên cứu đủ để đưa vào luận văn và bảo vệ.", en: "Produces research results ready for the thesis and defense." },
  },
  {
    id: "thesis",
    semester: 4,
    ru: "Подготовка и защита ВКР",
    title: { vi: "Chuẩn bị và bảo vệ luận văn tốt nghiệp", en: "Preparation and Defense of the Final Qualification Work" },
    credits: 9,
    hours: 324,
    contactHours: 0,
    assessment: "defense",
    kind: "thesis",
    analysis: { vi: "Khối tổng hợp cuối chương trình: viết, hoàn thiện và bảo vệ luận văn trước hội đồng.", en: "The final capstone: writing, completing and defending the thesis before the commission." },
    prepare: { vi: "Luận văn, code, dữ liệu, slide, demo và câu trả lời cho phản biện.", en: "Thesis, code, data, slides, demo and defense Q&A preparation." },
    outcome: { vi: "Hoàn thành yêu cầu tốt nghiệp bậc thạc sĩ.", en: "Completes the master's graduation requirement." },
  },
] as const;

export const program = {
  code: "09.04.01/11",
  universityRu: "МГТУ им. Н.Э. Баумана",
  universityVi: "Đại học Kỹ thuật Quốc gia Moskva Bauman",
  universityEn: "Bauman Moscow State Technical University",
  trackRu: "Искусственный интеллект в автоматизированных системах обработки информации и управления",
  trackVi: "Trí tuệ nhân tạo trong các hệ thống tự động xử lý thông tin và điều khiển",
  trackEn: "Artificial Intelligence in Automated Information Processing and Control Systems",
  department: "ИУ5",
  faculty: "ИУ",
  degree: { vi: "Thạc sĩ", en: "Master's degree" },
  duration: { vi: "2 năm · chính quy", en: "2 years · full-time" },
  credits: 120,
  hours: 4320,
  startYear: 2026,
} as const;

export function semesterCourses(semester: 1 | 2 | 3 | 4) {
  return courses.filter((course) => course.semester === semester);
}

export function yearCourses(year: 1 | 2) {
  return courses.filter((course) => year === 1 ? course.semester <= 2 : course.semester >= 3);
}
